# yaml-language-server: $schema=https://gitlab.com/gitlab-org/gitlab/-/raw/HEAD/app/assets/javascripts/editor/schema/ci.json

stages:
  - build
  - release
  - deploy

variables:
  TAG_IMAGE: $CI_COMMIT_TAG

build_pwa:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]{4}\.[0-9]{1,3}$/
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - echo "Building mobile application..."
    - docker build -t "$CI_REGISTRY_IMAGE/pwa:latest" -t "$CI_REGISTRY_IMAGE/pwa:$TAG_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE/pwa" --all-tags
    - echo "$CI_JOB_ID" > pwa_build_job_id.txt
  artifacts:
    paths:
      - pwa_build_job_id.txt

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - job: build_pwa
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]{4}\.[0-9]{1,3}$/
  variables:
    RELEASE_TITLE: "Release ${CI_COMMIT_TAG}"
    RELEASE_DESC: "Tagged after commit ${CI_COMMIT_SHORT_SHA}, message ${CI_COMMIT_TAG_MESSAGE}"
  script:
    - export PWA_BUILD_JOB_ID="$(cat pwa_build_job_id.txt)"
    - echo "create release ${CI_COMMIT_TAG} from jobs $PWA_BUILD_JOB_ID"
    - release-cli create --name "${RELEASE_TITLE}" --description "${RELEASE_DESC}" --tag-name "${CI_COMMIT_TAG}"

deploy-staging:
  stage: deploy
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]{4}\.[0-9]{1,3}$/
  before_script:
    - "which ssh-agent || ( apk update && apk add --no-cache openssh)"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - |
      ssh -p $SSH_PORT -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "
        export APP_IMAGE_STG_PWA=\"$CI_REGISTRY_IMAGE/pwa\" &&
        export APP_IMAGE_STG_PWA_TAG=$TAG_IMAGE

        cd ~/web/staging/umkmgo

        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
        docker compose -f docker-compose.stg.yml rm -f umkmgo-staging-pwa &&
        docker compose -f docker-compose.stg.yml pull umkmgo-staging-pwa &&
        docker compose -f docker-compose.stg.yml --profile pwa up -d --build
      "

deploy-production:
  stage: deploy
  image: alpine:latest
  rules:
    - if: $CI_COMMIT_TAG =~ /^v[0-9]{4}\.[0-9]{1,3}$/
  before_script:
    - "which ssh-agent || ( apk update && apk add --no-cache openssh)"
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 700 ~/.ssh/id_rsa
    - eval "$(ssh-agent -s)"
    - ssh-add ~/.ssh/id_rsa
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - |
      ssh -p $SSH_PORT -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} " 
        export APP_IMAGE_PROD_PWA=\"$CI_REGISTRY_IMAGE/pwa\" &&
        export APP_IMAGE_PROD_PWA_TAG=$CI_COMMIT_TAG &&

        cd ~/web/production/umkmgo

        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
        docker compose -f docker-compose.prod.yml rm -f umkmgo-production-pwa &&
        docker compose -f docker-compose.prod.yml pull umkmgo-production-pwa &&
        docker compose -f docker-compose.prod.yml --profile pwa up -d --build
      "
  when: manual
